name: Weekly Grocery Scraper

on:
  schedule:
    - cron: '0 8 * * 4'  # Every Thursday at 08:00 UTC
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd grocery_checker
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: |
          cd grocery_checker
          python main.py

      - name: Commit and push new data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "🛒 Update grocery data - $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push
